# Generated by Django 4.2.7 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tyil', models.DateTimeField()),
                ('manzil', models.TextField()),
            ],
        ),
    ]
